version: "3"
services:
  postgres:
    container_name: hashtag_postgres
    image: postgres:16-alpine
    volumes:
      - app_db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
  gethashtag-bot:
    container_name: hashtag_bot
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    restart: always
    depends_on:
      - postgres

volumes:
  app_db: