"""empty message

Revision ID: 37f1ba76c4d6
Revises: 95c8bcd4c095
Create Date: 2024-01-15 11:53:28.295049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f1ba76c4d6'
down_revision: Union[str, None] = '95c8bcd4c095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtag', sa.Column('category_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'hashtag', 'category_hashtag', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hashtag', type_='foreignkey')
    op.drop_column('hashtag', 'category_id')
    # ### end Alembic commands ###
