"""empty message

Revision ID: 7270f3249e44
Revises: 5241f9c855b5
Create Date: 2024-01-12 12:04:44.721475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7270f3249e44'
down_revision: Union[str, None] = '5241f9c855b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_hashtag', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'category_hashtag', 'telegram_message', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category_hashtag', type_='foreignkey')
    op.drop_column('category_hashtag', 'message_id')
    # ### end Alembic commands ###
