"""empty message

Revision ID: ae95590795d6
Revises: c96dcbf46109
Create Date: 2024-01-15 21:53:34.873055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae95590795d6'
down_revision: Union[str, None] = 'c96dcbf46109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_hashtag', sa.Column('message_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category_hashtag', 'telegram_message', ['message_id'], ['id'])
    op.alter_column('hashtag', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('telegram_message_category_id_fkey', 'telegram_message', type_='foreignkey')
    op.drop_column('telegram_message', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_message', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('telegram_message_category_id_fkey', 'telegram_message', 'category_hashtag', ['category_id'], ['id'])
    op.alter_column('hashtag', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'category_hashtag', type_='foreignkey')
    op.drop_column('category_hashtag', 'message_id')
    # ### end Alembic commands ###
