"""empty message

Revision ID: c96dcbf46109
Revises: 37f1ba76c4d6
Create Date: 2024-01-15 15:56:33.101806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96dcbf46109'
down_revision: Union[str, None] = '37f1ba76c4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chat', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'telegram_chat', 'telegram_message', ['message_id'], ['id'])
    op.add_column('telegram_message', sa.Column('category_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'telegram_message', 'category_hashtag', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_message', type_='foreignkey')
    op.drop_column('telegram_message', 'category_id')
    op.drop_constraint(None, 'telegram_chat', type_='foreignkey')
    op.drop_column('telegram_chat', 'message_id')
    # ### end Alembic commands ###
